name: hello-world
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo world
        run: echo "Hello World!"

  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List All Files
        run: ls -al